### ISSUE TITLE
Cookie based login will be deprecated soon. Does this library support OAuth?

### ISSUE THREAD

**Issue by clearitout** [samsymons/RedditKit.rb#40]
https://www.reddit.com/r/redditdev/comments/2ujhkr/important_api_licensing_terms_clarified/

**Comment by samsymons** [comment]
Wrote a reply to this here: https://github.com/samsymons/RedditKit/issues/61

**Comment by clearitout** [comment]
Oh sorry for the duplicate issue. Thanks for the response.

**Comment by samsymons** [comment]
No problem at all! I'll let you know once I have the OAuth support up for testing.
